### ISSUE TITLE
Type Error in FF background function

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#80]
after fixing #61 and introducing the personas with commit referenced below do get the following error after clicking the ON button

> TypeError: newLinks.map is not a function[Learn More]  background.js:152:14

**Comment by bensteUEM** [comment]
> currently only in Firefox-benste branch

**Comment by BrueckmannM** [comment]
I've analyzed your branch and found out that the error you get is a runtime exception caused by a call to maintainLinksToFollow() with a wrong parameter type passed to it.
The "map" function I use within maintainLinksToFollow is only defined for arrays. Therefore you always have to make sure that you pass an array with links to maintainLinksToFollow. Even in the case that you actually have only one link, put in an array first and pass that to the function call.

The wrong call in your branch seems to happen in line 66, that section where you generate a new URL from the library and pass that one directly to the maintainLinksToFollow function. That section has originally been commented out in my code, so the error didn't come up so far.

**Comment by bensteUEM** [comment]
will check ...

**Comment by bensteUEM** [comment]
guess you are talking about  line 77 in the current code
`	function handleLinks(links) {
		
		let actuallyAddedLinks = maintainLinksToFollow(links); `

**Comment by bensteUEM** [comment]
does no longer exist
